{
"openapi": "3.0.0",
  "info": {
    "title": "Basic API",
    "version": "1.0.1",
    "description": "A basic API that has toppings as a collection"
  },
"servers": [
  {
    "url": "http://localhost:4579",
    "description": "Localhost Server for testing the API"
  }
],
"paths": {
  "/toppings/getall": {
    "get": {
      "tags": [
        "toppings"
      ],
      "summary": "Get all toppings",
      "description": "Obtiene una lista con todos los toppings existentes",
      "parameters": [],
      "responses": {
        "200": {
          "description": "OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "no schema defined"
                },
                "example": {
                  "toppings": [
                      {
                        "_id": "1234",
                        "name": "carne",
                        "type": "Meat",
                        "available": true,
                        "imagen":"https://pixelartmaker-data-78746291193.nyc3.digitaloceanspaces.com/image/753ce060eea2ca1.png"
                      }
                  ]
                }
              }
            }
          }
        },
        "400": {
          "description": "NOT OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "no schema defined"
                },
                "example": {
                  "error": "Bad Request (could change)"
                }
              }
            }
          }
        }
      }
    }
  },
  "/toppings/create": {
    "post": {
      "tags": [
        "toppings"
      ],
      "summary": "Creates a topping",
      "description": "Crea un topping en la base de datos",
      "requestBody": { 
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/definitions/Topping"
            }
          }
        }
      },
      "responses": {
        "200": {
          "description": "OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "toppings": {
                    "name": "carne",
                    "type": "Meat",
                    "available": true,
                    "imagen": "https://pixelartmaker-data-78746291193.nyc3.digitaloceanspaces.com/image/753ce060eea2ca1.png"
                  }
                }
              }
            }
          }
        },
        "400": {
          "description": "NOT OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "error": "Bad Request (could change)"
                }
              }
            }
          }
        }
      }
    }
  },
  "/toppings/delete/{_id}": {
    "delete": {
      "tags": [
        "toppings"
      ],
      "summary": "Deletes a topping",
      "description": "Elimina un topping de la base de datos",
      "parameters": [
        {
          "in": "path",
          "name": "_id",
          "required": true,
          "schema": {
            "type": "string",
            "description": "Id of the topping to delete"
          }
        }
      ],
      "responses": {
        "200": {
          "description": "OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                    "msg": "deleted"
                }
              }
            }
          }
        },
        "400": {
          "description": "NOT OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "error": "Bad Request (could change)"
                }
              }
            }
          }
        }
      }
    }
  },
  "/toppings/update/{_id}": {
    "patch": {
      "tags": [
        "toppings"
      ],
      "summary": "Updates a topping",
      "description": "Actualiza un topping de la base de datos",
      "requestBody": {
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/definitions/Test"
            }
          }
        }
      },
      "parameters": [
        {
          "name": "_id",
          "in": "path",
          "required": true,
          "description": "Id of the topping to update",
          "schema": {
            "type": "string"
          }
        }
      ],
      "responses": {
        "200": {
          "description": "OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "msg": "updated"
                }
              }
            }
          }
        },
        "400": {
          "description": "NOT OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "error": "Bad Request (could change)"
                }
              }
            }
          }
        },
        "404": {
          "description": "NOT FOUND",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "error": "Id Not Found"
                }
              }
            }
          }
        }
      }
    }
  },
  "/quesos/getall": {
    "get": {
      "tags": [
        "quesos"
      ],
      "summary": "Get all Cheeses",
      "description": "Obtiene una lista con todos los quesos existentes",
      "parameters": [],
      "responses": {
        "200": {
          "description": "OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/definitions/Quesos"
                },
                "example": {
                  "quesos": [
                    {
                      "_id": "1234",
                      "name": "queso",
                      "description": "Este es un quesito",
                      "available": true,
                      "imagen":"https://images.unsplash.com/photo-1559560923-3b80329ea420?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=320&ixid=MnwxfDB8MXxyYW5kb218MHx8Y2hlZXNlfHx8fHx8MTY5NjQyNzY0Nw&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=320"
                    }
                  ]
                }
              }
            }
          }
        },
        "400": {
          "description": "NOT OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "no schema defined"
                },
                "example": {
                  "error": "Bad Request (could change)"
                }
              }
            }
          }
        }
      }
    }
  },
  "/quesos/create": {
    "post": {
      "tags": [
        "quesos"
      ],
      "summary": "Creates a Cheese",
      "description": "Crea un quesito en la base de datos",
      "requestBody": { 
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/definitions/Quesos"
            }
          }
        }
      },
      "responses": {
        "200": {
          "description": "OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "msg": "created successfully"
                }
              }
            }
          }
        },
        "400": {
          "description": "NOT OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "error": "Bad Request (could change)"
                }
              }
            }
          }
        }
      }
    }
  },
  "/quesos/delete/{_id}": {
    "delete": {
      "tags": [
        "quesos"
      ],
      "summary": "Deletes a Cheese",
      "description": "Elimina un quesito de la base de datos",
      "parameters": [
        {
          "name": "_id",
          "in": "path",
          "required": true,
          "description": "Id of the Cheese to delete",
          "schema": {
            "type": "string"
          }
        }
      ],
      "responses": {
        "200": {
          "description": "OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "msg": "deleted successfully"
                }
              }
            }
          }
        },
        "400": {
          "description": "NOT OK", 
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "error": "Bad Request (could change)"
                }
              }
            }
          }
        }
      }
    }
  },
  "/quesos/update/{_id}": {
    "patch": {
      "tags": [
        "quesos"
      ],
      "summary": "Updates a Cheese",
      "description": "Actualiza un quesito de la base de datos",
      "parameters": [
        {
          "name": "_id",
          "in": "path",
          "required": true,
          "description": "Id of the Cheese to update",
          "schema": {
            "type": "string"
          }
        }
      ],
      "requestBody": {
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/definitions/Quesos"
            }
          }
        }
      },
      "responses": {
        "200": {
          "description": "OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "msg": "updated successfully"
                }
              }
            }
          }
        },
        "400": {
          "description": "NOT OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "error": "Bad Request (could change)"
                }
              }
            }
          }
        }
      }
    }
  },
  "/salsas/getall": {
    "get": {
      "tags": [
        "salsas"
      ],
      "summary": "Get all Salsas",
      "description": "Obtiene una lista con todos las salsas existentes",
      "parameters":[],
      "responses": {
        "200": {
          "description": "OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/definitions/Salsas"
                },
                "example": {
                  "salsas": [
                    {
                      "_id": "1234",
                      "name": "salsa",
                      "type": "Salsa",
                      "available": true,
                      "imagen":"https://pixelartmaker-data-78746291193.nyc3.digitaloceanspaces.com/image/753ce060eea2ca1.png"
                    }
                  ]
                }
              }
            }
          }
        },
        "400": {
          "description": "NOT OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "error": "Bad Request (could change)"
                }
              }
            }
          }
        }
      }
    }
  },
  "/salsas/create": {
    "post": {
      "tags": [
        "salsas"
      ],
      "summary": "Creates a Salsa",
      "description": "Crea una salsa en la base de datos",
      "requestBody": {
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/definitions/Salsas"
            }
          }
        }
      },
      "responses": {
        "200": {
          "description": "OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "msg": "created successfully"
                }
              }
            }
          }
        },
        "400": {
          "description": "NOT OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "error": "Bad Request (could change)"
                }
              }
            }
          }
        }
      }
    }
  },
  "/salsas/delete/{_id}": {
    "delete": {
      "tags": [
        "salsas"
      ],
      "summary": "Deletes a Salsa",
      "description": "Elimina una salsa de la base de datos",
      "parameters": [
        {
          "name": "_id",
          "in": "path",
          "required": true,
          "description": "Id of the Salsa to delete",
          "schema": {
            "type": "string"
          }
        }
      ],
      "responses": {
        "200": {
          "description": "OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "msg": "deleted successfully"
                }
              }              
            }
          }
        },
        "400": {
          "description": "NOT OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "error": "Bad Request (could change)"
                }
              }
            }
          }
        }
      }
    }
  },
  "/salsas/update/{_id}": {
    "patch": {
      "tags": [
        "salsas"
      ],
      "summary": "Updates a Salsa",
      "description": "Actualiza una salsa de la base de datos",
      "parameters": [
        {
          "name": "_id",
          "in": "path",
          "required": true,
          "description": "Id of the Salsa to update",
          "schema": {
            "type": "string"
          }
        }
      ],
      "requestBody": {
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/definitions/Salsas"
            }
          }
        }
      },
      "responses": {
        "200": {
          "description": "OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "msg": "updated successfully"
                }
              }
            }
          }
        },
        "400": {
          "description": "NOT OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "error": "Bad Request (could change)"
                }
              }
            }
          }
        }
      }
    }
  },
  "/bordes/getall": {
    "get": {
      "tags": [
        "bordes"
      ],
      "summary": "Get all Bordes",
      "description": "Obtiene una lista con todos los bordes existentes",
      "parameters":[],
      "responses": {
        "200": {
          "description": "OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/definitions/Bordes"
                }
              }
            }
          }
        },
        "400": {
          "description": "NOT OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "error": "Bad Request (could change)"
                }
              }
            }
          }
        }
      }
    }
  },
  "/bordes/create": {
    "post": {
      "tags": [
        "bordes"
      ],
      "summary": "Creates a Borde",
      "description": "Crea un borde en la base de datos",
      "requestBody": {
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/definitions/Bordes"
            }
          }
        }
      },
      "responses": {
        "200": {
          "description": "OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "msg": "created successfully"
                }
              }
            }
          }
        },
        "400": {
          "description": "NOT OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "error": "Bad Request (could change)"
                }
              }
            }
          }
        }
      }
    }
  },
  "/bordes/delete/{_id}": {
    "delete": {
      "tags": [
        "bordes"
      ],
      "summary": "Deletes a Borde",
      "description": "Elimina un borde de la base de datos",
      "parameters": [
        {
          "name": "_id",
          "in": "path",
          "required": true,
          "description": "Id of the Borde to delete",
          "schema": {
            "type": "string"
          }
        }
      ],
      "responses": {
        "200": {
          "description": "OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "msg": "deleted successfully"
                }
              }
            }
          }
        },
        "400": {
          "description": "NOT OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "error": "Bad Request (could change)"
                }
              }
            }
          }
        }
      }
    }
  },
  "/bordes/update/{_id}": {
    "patch": {
      "tags": [
        "bordes"
      ],
      "summary": "Updates a Borde",
      "description": "Actualiza un borde de la base de datos",
      "parameters": [
        {
          "name": "_id",
          "in": "path",
          "required": true,
          "description": "Id of the Borde to update",
          "schema": {
            "type": "string"
          }
        }
      ],
      "requestBody": {
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/definitions/Bordes"
            }
          }
        }
      },
      "responses": {
        "200": {
          "description": "OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "msg": "updated successfully"
                }
              }
            }
          }
        },
        "400": {
          "description": "NOT OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "error": "Bad Request (could change)"
                }
              }
            }
          }
        }
      }
    }
  },
  "/acomp/getall": {
    "get": {
    "summary": "Obtener todos los acompañamientos",
    "tags": ["Acompañamientos"],
    "responses": {
      "200": {
        "description": "Lista de acompañamientos obtenida exitosamente",
        "content": {
          "application/json": {
            "example": [
              {
                "_id": "60726eb22a0c1b001f7e2c5e",
                "name": "Acompañamiento 1",
                "description": "Descripción del Acompañamiento 1",
                "available": true,
                "imagen": "https://ejemplo.com/imagen1.jpg"
              },
              {
                "_id": "60726eb22a0c1b001f7e2c5f",
                "name": "Acompañamiento 2",
                "description": "Descripción del Acompañamiento 2",
                "available": false,
                "imagen": "https://ejemplo.com/imagen2.jpg"
              }
            ]
          }
        }
      },
      "400": {
        "description": "Error al obtener la lista de acompañamientos"
      }
    }
    }
  },
  "/acomp/create": {
    "post": {
    "summary": "Crear un nuevo acompañamiento",
    "tags": ["Acompañamientos"],
    "requestBody": {
      "description": "Datos del acompañamiento a crear",
      "required": true,
      "content": {
        "application/json": {
          "example": {
            "name": "Nuevo Acompañamiento",
            "description": "Descripción del Nuevo Acompañamiento",
            "available": true,
            "imagen": "https://ejemplo.com/imagen3.jpg"
          }
        }
      }
    },
    "responses": {
      "200": {
        "description": "Acompañamiento creado exitosamente",
        "content": {
          "application/json": {
            "example": {
              "msg": "Acompañamiento creado",
              "data": {
                "_id": "60726eb22a0c1b001f7e2c60",
                "name": "Nuevo Acompañamiento",
                "description": "Descripción del Nuevo Acompañamiento",
                "available": true,
                "imagen": "https://ejemplo.com/imagen3.jpg"
              }
            }
          }
        }
      },
      "400": {
        "description": "Error al crear el acompañamiento"
      }
    }
    }
  },
  "/acomp/update/{id}": {
    "patch": {
    "summary": "Actualizar un acompañamiento existente",
    "tags": ["Acompañamientos"],
    "parameters": [
      {
        "in": "path",
        "name": "id",
        "required": true,
        "schema": {
          "type": "string"
        },
        "description": "ID del acompañamiento a actualizar"
      }
    ],
    "requestBody": {
      "description": "Nuevos datos del acompañamiento",
      "required": true,
      "content": {
        "application/json": {
          "example": {
            "name": "Acompañamiento Actualizado",
            "description": "Descripción Actualizada",
            "available": false,
            "imagen": "https://ejemplo.com/imagen4.jpg"
          }
        }
      }
    },
    "responses": {
      "200": {
        "description": "Acompañamiento actualizado exitosamente",
        "content": {
          "application/json": {
            "example": {
              "msg": "Acompañamiento actualizado",
              "data": {
                "_id": "60726eb22a0c1b001f7e2c60",
                "name": "Acompañamiento Actualizado",
                "description": "Descripción Actualizada",
                "available": false,
                "imagen": "https://ejemplo.com/imagen4.jpg"
              }
            }
          }
        }
      },
      "400": {
        "description": "Error al actualizar el acompañamiento"
      }
    }
      }
  },
  "/acomp/delete/{id}": {
    "delete": {
    "summary": "Eliminar un acompañamiento existente",
    "tags": ["Acompañamientos"],
    "parameters": [
      {
        "in": "path",
        "name": "id",
        "required": true,
        "schema": {
          "type": "string"
        },
        "description": "ID del acompañamiento a eliminar"
      }
    ],
    "responses": {
      "200": {
        "description": "Acompañamiento eliminado exitosamente",
        "content": {
          "application/json": {
            "example": {
              "msg": "Acompañamiento eliminado",
              "data": {
                "_id": "60726eb22a0c1b001f7e2c60",
                "name": "Acompañamiento Eliminado",
                "description": "Descripción Eliminada",
                "available": false,
                "imagen": "https://ejemplo.com/imagen4.jpg"
              }
            }
          }
        }
      },
      "400": {
        "description": "Error al eliminar el acompañamiento"
      }
    }
    }
  }
},
"definitions": {
  "Topping": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "example": "carne"
      },
      "type": {
        "type": "string",
        "enum": ["Meat", "Vegetable"],
        "example": "Meat"
      },
      "available": {
        "type": "boolean",
        "example": true
      },
      "imagen": {
        "type": "string",
        "example": "https://pixelartmaker-data-78746291193.nyc3.digitaloceanspaces.com/image/753ce060eea2ca1.png"
      }
    }
  },
  "Test": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "example": "Test Topping"
      },
      "type": {
        "type": "string",
        "enum": ["Test"],
        "example": "Test"
      },
      "available": {
        "type": "boolean",
        "example": true
      },
      "imagen": {
        "type": "string",
        "example": "Test.png"
      }
    }
  },
  "Quesos": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "example": "Queso"
      },
      "description": {
        "type": "string",
        "example": "Esta es la descripcion de un dato relacionado con quesos"  
      },
      "available": {
        "type": "boolean",
        "example": true
      },
      "imagen": {
        "type": "string",
        "example": "https://images.unsplash.com/photo-1559560923-3b80329ea420?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=320&ixid=MnwxfDB8MXxyYW5kb218MHx8Y2hlZXNlfHx8fHx8MTY5NjQyNzY0Nw&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=320"
      }
    }
  },
  "Salsas": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "example": "Salsa"
      },
      "description": {
        "type": "string",
        "example": "Esta es la descripcion de un dato relacionado con salsas"    
      },
      "available": {
        "type": "boolean",
        "example": true
      },
      "imagen": {
        "type": "string",
        "example":"https://santaisabel.vtexassets.com/arquivos/ids/199191-360-360?width=360&height=360&aspect=true"
      }
    }
  },
  "Bordes": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "example": "Borde"
      },
      "description": {
        "type": "string",
        "example": "Esta es la descripcion de un dato relacionado con bordes"
      },
      "available": {
        "type": "boolean",
        "example": true
      },
      "imagen": {
        "type": "string",
        "example": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3YpvCD0bp8_jkpMoMiN5lnr-hZTjJsKQ4bsEnj4wSdOo805ainPab2sqvphJgFRidQ8o&usqp=CAU"
      }
    }
  }
}
}